version: '3.8'
services:
  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db
  backend:
    build: .
    command: npm run dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=mongodb://root:example@mongo:27017/athena_bank?authSource=admin
      - JWT_SECRET=supersecretkey
    depends_on:
      - mongo
volumes:
  mongo_data:
